repos:
  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet format
        entry: dotnet format --verify-no-changes
        language: system
        pass_filenames: false

      - id: dotnet-analyzers
        name: dotnet analyzers
        entry: dotnet format analyzers --verify-no-changes
        language: system
        pass_filenames: false
